# Generated by Django 4.2.13 on 2024-05-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='name',
            field=models.CharField(default='House', help_text='name of house, this can be anything unique', max_length=100, unique=True),
        ),
    ]
