# Generated by Django 4.2.13 on 2024-05-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_houses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='House', help_text='name of house, this can be anything unique', max_length=100, unique=True)),
                ('staus', models.CharField(choices=[('liked', 'Liked'), ('viewed', 'Viewed'), ('dislike', 'Dislike'), ('maybe', 'Maybe')], max_length=20)),
                ('link', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Houses',
        ),
    ]
