# Generated by Django 4.2.13 on 2024-05-08 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_house_delete_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='staus',
            field=models.CharField(choices=[('liked', 'Liked'), ('dislike', 'Dislike'), ('maybe', 'Maybe'), ('viewed', 'Viewed'), ('offered', 'Offered')], max_length=20),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.house')),
            ],
        ),
    ]
