# Generated by Django 4.2.13 on 2024-05-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_house_staus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.image'),
        ),
    ]
