# Generated by Django 4.2.13 on 2024-05-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_house_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ManyToManyField(null=True, to='core.image'),
        ),
    ]
