# Generated by Django 4.2.13 on 2024-05-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_house_image_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
