# Generated by Django 4.2.13 on 2024-05-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='staus',
            new_name='status',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
