# Generated by Django 4.2.13 on 2024-05-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_staus_house_status_house_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(blank=True, help_text='name of house, this can be anything unique', max_length=100, null=True, unique=True),
        ),
    ]
