# Generated by Django 4.2.13 on 2024-05-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_house_image_house_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.image'),
        ),
    ]
