# Generated by Django 4.2.13 on 2024-05-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_house_date_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='address',
            new_name='postcode',
        ),
    ]
