# Generated by Django 4.2.13 on 2024-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_image_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sample_image',
            field=models.ImageField(default='media/image_uploads/DJI_0062.JPG', upload_to='media/image_uploads'),
        ),
    ]
